extends:
  - airbnb-base
  - plugin:lodash-fp/recommended

parser: babel-eslint

plugins:
  - lodash-fp

rules:
  import/prefer-default-export: off
  lodash-fp/consistent-compose:
    - error
    - pipe
